spring:
  datasource:
    url: jdbc:postgres://localhost:5432/pkch
    username: pkch
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug
server:
  port: 8080
